<?php
/*
Plugin Name: Ibexrentacar
Plugin URI: http://www.ibexrentacar.com/
Description: Plugin de WordPress para conectar tu blog con la plataforma de gestión de Ibexrentacar.
Version: 1.7
Author: Ibexestudio
Author URI: http://www.ibexrentacar.com
*/
?>
<?php $active_tab = "dashboard"; if(isset($_GET['tab']))$active_tab = $_GET['tab']; if(!$this->is_ws_logged && ($active_tab=="shortcode" || $active_tab=="import"))$active_tab = "settings"; ?><h2 class="nav-tab-wrapper"> <a href="?page=ibexrentacar&tab=dashboard" class="nav-tab <?php  echo $active_tab == 'dashboard' ? 'nav-tab-active' : ''; ?>"><?php  echo _irct("Dashboard") ?></a> <?php  if($this->is_ws_logged){?><a href="?page=ibexrentacar&tab=shortcode" class="nav-tab <?php  echo $active_tab == 'shortcode' ? 'nav-tab-active' : ''; ?>"><?php  echo _irct("Integración") ?></a><?php  }?> <?php  if($this->is_ws_logged){?><a href="?page=ibexrentacar&tab=import" class="nav-tab <?php  echo $active_tab == 'import' ? 'nav-tab-active' : ''; ?>"> <div class="ircpleft"><?php  echo _irct("Importar") ?></div> <div class="ircpright"><img id="ircp_alert_tabimport" src="<?php  echo $this->plugin_url.'/img/newalert.png' ?>" style="width:12px; display:none;margin: 5px 0 0 5px;" /></div> <div class="ircpclear"></div> <?php  }?> <a href="?page=ibexrentacar&tab=settings" class="nav-tab <?php  echo $active_tab == 'settings' ? 'nav-tab-active' : ''; ?>"> <div class="ircpleft"><?php  echo _irct("Ajustes") ?></div> <div class="ircpright"><img id="ircp_alert_tabsettings" src="<?php  echo $this->plugin_url.'/img/alert.png' ?>" style="width:12px; display:none;margin: 5px 0 0 5px;" /></div> <div class="ircpclear"></div> </a> <a href="?page=ibexrentacar&tab=irc" class="nav-tab <?php  echo $active_tab == 'irc' ? 'nav-tab-active' : ''; ?>"><?php  echo _irct("Documentación") ?></a> <a href="?page=ibexrentacar&tab=support" class="nav-tab <?php  echo $active_tab == 'support' ? 'nav-tab-active' : ''; ?>"><?php  echo _irct("Soporte") ?></a> <?php   ?></h2><div id="ircpmenumobilebox"> <select id="ircpmenumobile" onchange="ircpmobile(this.value)"> <option value="dashboard" <?php  echo $active_tab == 'dashboard' ? 'selected="selected"' : ''; ?>><?php  echo _irct("Dashboard") ?></option> <?php  if($this->is_ws_logged){?><option value="shortcode" <?php  echo $active_tab == 'shortcode' ? 'selected="selected"' : ''; ?>><?php  echo _irct("Integración") ?></option><?php  }?> <?php  if($this->is_ws_logged){?><option value="import" <?php  echo $active_tab == 'import' ? 'selected="selected"' : ''; ?>><?php  echo _irct("Importar") ?></option><?php  }?> <option value="settings" <?php  echo $active_tab == 'settings' ? 'selected="selected"' : ''; ?>><?php  echo _irct("Ajustes") ?></option> <option value="irc" <?php  echo $active_tab == 'irc' ? 'selected="selected"' : ''; ?>><?php  echo _irct("Documentación") ?></option> <option value="support" <?php  echo $active_tab == 'support' ? 'selected="selected"' : ''; ?>><?php  echo _irct("Soporte") ?></option> <?php  ?> </select></div>